[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# ~/.config/yazi/keymap.toml
[[mgr.prepend_keymap]]
on = "<C-m>"
run = 'shell --block -- neomutt -a "$@"'

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"
