[mgr]
linemode = "size"

[opener]
edit = [
  { run = 'nvim "$@"', desc = "nvim", block = true, for = "unix" },
]
pdff = [
  { run = 'setsid zathura "$@" >/dev/null 2>&1 &', desc = "zathura", orphan = true, for = "unix" },
]
images = [
  { run = 'feh "$@"', desc = "feh", block = true, for = "unix" },
]
mathematica = [
  { run = '/usr/local/bin/WolframNB "$@"', desc = "WolframNB", orphan = true, for = "unix" },
]
reveal = [
  { run = "xdg-open %d1", desc = "Reveal", for = "linux" },
]

[open]
rules = [
  # Priority Binary Types
  { mime = "application/pdf", use = ["pdff", "reveal"] },
  { mime = "image/png", use = ["images"] },
  { mime = "image/jpeg", use = ["images"] },
  { mime = "text/*", use = "edit" },
  { name = "*.djvu", mime = "*", use = ["pdff"] },
  { mime = "image/*", use = ["images"] },
  { mime = "application/vnd.wolfram.mathematica", use = "mathematica" },

  # Fallback for all other text
  { url = "*", use = "edit" },
]
